name: eda
channels:
  - plotly
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - a2wsgi=1.10.10
  - aiologic=0.14.0
  - aiosqlite=0.21.0
  - airflow=3.0.3
  - alembic=1.16.4
  - annotated-types=0.7.0
  - anyio=4.9.0
  - apache-airflow=3.0.3
  - apache-airflow-core=3.0.3
  - apache-airflow-providers-common-compat=1.7.3
  - apache-airflow-providers-common-io=1.6.2
  - apache-airflow-providers-common-sql=1.27.4
  - apache-airflow-providers-smtp=2.1.2
  - apache-airflow-providers-standard=1.5.0
  - apache-airflow-task-sdk=1.0.3
  - appdirs=1.4.4
  - appnope=0.1.4
  - argcomplete=3.6.2
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asgiref=3.9.1
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - automat=25.4.16
  - babel=2.17.0
  - backoff=2.2.1
  - backports.strenum=1.3.1
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.17.1
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cadwyn=5.4.4
  - cartopy=0.24.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - colour=0.1.5
  - comm=0.2.3
  - constantly=15.1.0
  - contourpy=1.3.3
  - cron-descriptor=1.4.5
  - croniter=6.0.0
  - cryptography=45.0.5
  - cssselect=1.3.0
  - cycler=0.12.1
  - dash=3.0.4
  - debugpy=1.8.15
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - dill=0.4.0
  - dnspython=2.3.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - et_xmlfile=2.0.0
  - eval-type-backport=0.2.2
  - eval_type_backport=0.2.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fastapi=0.116.1
  - fastapi-cli=0.0.8
  - fastapi-core=0.116.1
  - filelock=3.18.0
  - flask=3.1.1
  - folium=0.20.0
  - fonttools=4.59.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - freexl=2.0.0
  - fsspec=2025.7.0
  - furl=2.1.4
  - geopandas=1.1.0
  - geopandas-base=1.1.0
  - geos=3.13.1
  - giflib=5.2.2
  - googleapis-common-protos=1.70.0
  - greenlet=3.2.3
  - grpcio=1.71.0
  - gunicorn=23.0.0
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.13.0
  - hdf5=1.14.3
  - hpack=4.1.0
  - html5lib=1.1
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - hyperlink=21.0.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - incremental=24.7.2
  - infinity=1.5
  - intervals=0.9.2
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - itemadapter=0.12.0
  - itemloaders=1.3.2
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.1
  - json-c=0.18
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lark=1.2.2
  - lazy-object-proxy=1.11.0
  - lcms2=2.17
  - lerc=4.0.0
  - levenshtein=0.27.1
  - libabseil=20250127.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcst=1.8.2
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgdal-core=3.11.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgrpc=1.71.0
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - libre2-11=2025.06.26
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.3
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - linkify-it-py=2.0.3
  - llvm-openmp=20.1.8
  - lockfile=0.12.2
  - lxml=6.0.0
  - lz4-c=1.10.0
  - lzo=2.10
  - mako=1.3.10
  - mapclassify=2.10.0
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - methodtools=0.4.7
  - minizip=4.0.10
  - mistune=3.1.3
  - more-itertools=10.7.0
  - msgspec=0.19.0
  - munkres=1.1.4
  - muparser=2.3.5
  - mysql=9.3.0
  - mysql-client=9.3.0
  - mysql-common=9.3.0
  - mysql-connector-python=8.4.0
  - mysql-devel=9.3.0
  - mysql-libs=9.3.0
  - mysql-server=9.3.0
  - narwhals=2.0.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - numexpr=2.10.2
  - numpy=2.3.2
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.2
  - opentelemetry-api=1.36.0
  - opentelemetry-exporter-otlp=1.36.0
  - opentelemetry-exporter-otlp-proto-common=1.36.0
  - opentelemetry-exporter-otlp-proto-grpc=1.36.0
  - opentelemetry-exporter-otlp-proto-http=1.36.0
  - opentelemetry-proto=1.36.0
  - opentelemetry-sdk=1.36.0
  - opentelemetry-semantic-conventions=0.57b0
  - orderedmultidict=1.0.1
  - outcome=1.3.0.post0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parsel=1.10.0
  - parso=0.8.4
  - passlib=1.7.4
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.45
  - pendulum=3.1.0
  - pexpect=4.9.0
  - phonenumbers=9.0.10
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - platformdirs=4.3.8
  - plotly=6.0.0
  - pluggy=1.6.0
  - portaudio=19.7.0
  - proj=9.6.2
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - protego=0.5.0
  - protobuf=5.29.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydispatcher=2.0.5
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyobjc-core=11.1
  - pyobjc-framework-cocoa=11.1
  - pyogrio=0.11.0
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyshp=2.4.0
  - pysocks=1.7.1
  - pytables=3.10.2
  - python=3.12.11
  - python-daemon=3.1.2
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-levenshtein=0.27.1
  - python-multipart=0.0.20
  - python-slugify=8.0.4
  - python-sounddevice=0.5.2
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - queuelib=1.8.0
  - rapidfuzz=3.13.0
  - re2=2025.06.26
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - requests-file=2.1.0
  - retryhttp=1.3.3
  - retrying=1.4.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - rich-argparse=1.7.1
  - rich-toolkit=0.14.9
  - rpds-py=0.26.0
  - scikit-learn=1.7.1
  - scipy=1.15.2
  - scrapy=2.13.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - selenium=4.32.0
  - selenium-manager=4.32.0
  - send2trash=1.8.3
  - service-identity=24.2.0
  - service_identity=24.2.0
  - setproctitle=1.3.6
  - setuptools=80.9.0
  - shapely=2.1.1
  - shellingham=1.5.4
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.7
  - sqlalchemy=1.4.54
  - sqlalchemy-jsonfield=1.0.1.post0
  - sqlalchemy-utils=0.41.2
  - sqlalchemy-utils-arrow=0.41.2
  - sqlalchemy-utils-babel=0.41.2
  - sqlalchemy-utils-base=0.41.2
  - sqlalchemy-utils-color=0.41.2
  - sqlalchemy-utils-encrypted=0.41.2
  - sqlalchemy-utils-intervals=0.41.2
  - sqlalchemy-utils-password=0.41.2
  - sqlalchemy-utils-pendulum=0.41.2
  - sqlalchemy-utils-phone=0.41.2
  - sqlalchemy-utils-timezone=0.41.2
  - sqlalchemy-utils-url=0.41.2
  - sqlite=3.50.3
  - sqlparse=0.5.3
  - stack_data=0.6.3
  - starlette=0.47.2
  - statsmodels=0.14.5
  - structlog=25.4.0
  - svcs=25.1.0
  - tabulate=0.9.0
  - tenacity=9.1.2
  - termcolor=3.1.0
  - terminado=0.18.1
  - text-unidecode=1.3
  - thefuzz=0.22.1
  - threadpoolctl=3.6.0
  - time-machine=2.17.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tldextract=5.3.0
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - trio=0.30.0
  - trio-websocket=0.12.2
  - twisted=25.5.0
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - types-python-dateutil=2.9.0.20250708
  - types-requests=2.32.4.20250611
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - unicodedata2=16.0.0
  - universal-pathlib=0.2.6
  - universal_pathlib=0.2.6
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - uuid6=2025.0.1
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - w3lib=2.3.1
  - watchfiles=1.1.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webdriver-manager=4.0.2
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wirerope=1.0.0
  - wrapt=1.17.2
  - wsproto=1.2.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.4
  - zope.interface=7.2
  - zstandard=0.23.0
  - zstd=1.5.7
